USE dont_starve;
INSERT INTO Category (ID, txtid, name, image_path, description, expansion_id, is_character_specific, character_name) VALUES
	(0,'tools','Tools','images/categories/tools.png','',0,0,null),
	(1,'light','Light','images/categories/light.png','',0,0,null),
	(2,'nautical','Nautical','images/categories/nautical.png','',3,0,null),
	(3,'survival','Survival','images/categories/survival.png','',0,0,null),
	(4,'food','Food','images/categories/food.png','',0,0,null),
	(5,'science','Science','images/categories/science.png','',0,0,null),
	(6,'fight','Fight','images/categories/fight.png','',0,0,null),
	(7,'structures','Structures','images/categories/structures.png','',0,0,null),
	(8,'refine','Refine','images/categories/refine.png','',0,0,null),
	(9,'magic','Magic','images/categories/magic.png','',0,0,null),
	(10,'dress','Dress','images/categories/dress.png','',0,0,null),
	(11,'books','Books','images/categories/books.png','',1,1,5),
	(12,'tinkering','Tinkering','images/categories/tinkering.png','',0,1,9),
	(13,'ancient','Ancient','images/categories/ancient.png','',0,0,null),
	(14,'volcanic','Volcanic','images/categories/volcanic.png','',3,0,null),
	(15,'treasure_hunting','Treasure Hunting','images/categories/treasure_hunting.png','',4,0,null),
	(16,'green_thumb','Green Thumb','images/categories/green_thumb.png','',4,1,17),
	(17,'city_planning','City Planning','images/categories/city_planning.png','',4,0,null),
    (18,'engineering','Engineering','images/categories/engineering.png','',1,1,19),
    (19,'seafaring','Seafaring','images/categories/seafaring.png','',1,0,null),
    (20,'shadow','Shadow','images/categories/shadow.png','',1,1,8),
    (21,'cartography','Cartography','images/categories/cartograpy.png','',1,0,null),
    (22,'celestial','Celestial','images/categories/celestial.png','',1,0,null),
    (23,'critters','Critters','images/categories/critters.png','',1,0,null),
    (24,'sculpt','Sculpt','images/categories/sculpt.png','',1,0,null);