USE dont_starve;
INSERT INTO Materials (ID, txtid, name, image, is_craftable, recipe_id) VALUES
(0, 'cut_grass', 'Cut Grass', 'cut_grass.png', 0, null),
(1, 'flint', 'Flint', 'flint.png', 0, null),
(2, 'gold_nugget', 'Gold Nugget', 'gold_nugget.png', 0, null),
(3, 'log', 'Log', 'log.png', 0, null),
(4, 'rocks', 'Rocks', 'rocks.png', 0, null),
(5, 'twigs', 'Twigs', 'twigs.png', 0, null),
(6, 'fireflies', 'Fireflies', 'fireflies.png', 0, null),
(7, 'pumpkin', 'Pumpkin', 'pumpkin.png', 0, null),
(8, 'lightbulb', 'Lightbulb', 'lightbulb.png', 0, null),
(9, 'nitre', 'Nitre', 'nitre.png', 0, null),
(10, 'glow_berry', 'Glow Berry', 'glow_berry.png', 0, null),
(11, 'moleworm', 'Moleworm', 'moleworm.png', 0, null),
(12, 'silk', 'Silk', 'silk.png', 0, null),
(13, 'spider_gland', 'Spider Gland', 'spider_gland.png', 0, null),
(14, 'ashes', 'Ashes', 'ashes.png', 0, null),
(15, 'pig_skin', 'Pig Skin', 'pig_skin.png', 0, null),
(16, 'honey', 'Honey', 'honey.png', 0, null),
(17, 'bunny_puff', 'Bunny Puff', 'bunny_puff.png', 0, null),
(18, 'petals', 'Petals', 'petals.png', 0, null),
(19, 'down_feather', 'Down Feather', 'down_feather.png', 0, null),
(20, 'cut_reeds', 'Cut Reeds', 'cut_reeds.png', 0, null),
(21, 'gears', 'Gears', 'gears.png', 0, null),
(22, 'thick_fur', 'Thick Fur', 'thick_fur.png', 0, null),
(23, 'manure', 'Manure', 'manure.png', 0, null),
(24, 'honeycomb', 'Honeycomb', 'honeycomb.png', 0, null),
(25, 'bee', 'Bee', 'bee.png', 0, null),
(26, 'charcoal', 'Charcoal', 'charcoal.png', 0, null),
(27, 'bone_shards', 'Bone Shards', 'bone_shards.png', 0, null),
(28, 'nightmare_fuel', 'Nightmare Fuel', 'nightmare_fuel.png', 0, null),
(29, 'rotten_eggs', 'Rotten Eggs', 'rotten_eggs.png', 0, null),
(30, 'ice', 'Ice', 'ice.png', 0, null),
(31, 'azure_feather', 'Azure Feather', 'azure_feather.png', 0, null),
(32, 'crimson_feather', 'Crimson Feather', 'crimson_feather.png', 0, null),
(33, 'jet_feather', 'Jet Feather', 'jet_feather.png', 0, null),
(34, 'hounds_tooth', 'Hound''s Tooth', 'hounds_tooth.png', 0, null),
(35, 'marble', 'Marble', 'marble.png', 0, null),
(36, 'scales', 'Scales', 'scales.png', 0, null),
(37, 'volt_goat_horn', 'Volt Goat Horn', 'volt_goat_horn.png', 0, null),
(38, 'stinger', 'Stinger', 'stinger.png', 0, null),
(39, 'carrot', 'Carrot', 'carrot.png', 0, null),
(40, 'foliage', 'Foliage', 'foliage.png', 0, null),
(41, 'rocky_turf', 'Rocky Turf', 'rocky_turf.png', 0, null),
(42, 'seeds', 'Seeds', 'seeds.png', 0, null),
(43, 'beefalo_wool', 'Beefalo Wool', 'beefalo_wool.png', 0, null),
(44, 'broken_shell', 'Broken Shell', 'broken_shell.png', 0, null),
(45, 'dark_petals', 'Dark Petals', 'dark_petals.png', 0, null),
(46, 'red_gem', 'Red Gem', 'red_gem.png', 0, null),
(47, 'blue_gem', 'Blue Gem', 'blue_gem.png', 0, null),
(48, 'purple_gem', 'Purple Gem', 'purple_gem.png', 0, null),
(49, 'batlisk_wing', 'Batlisk Wing', 'batlisk_wing.png', 0, null),
(50, 'beard_hair', 'Beard Hair', 'beard_hair.png', 0, null),
(51, 'cooked_meat', 'Cooked Meat', 'cooked_meat.png', 0, null),
(52, 'living_log', 'Living Log', 'living_log.png', 0, null),
(53, 'mandrake', 'Mandrake', 'mandrake.png', 0, null),
(54, 'rabbit', 'Rabbit', 'rabbit.png', 0, null),
(55, 'slurper_pelt', 'Slurper Pelt', 'slurper_pelt.png', 0, null),
(56, 'beefalo_horn', 'Beefalo Horn', 'beefalo_horn.png', 0, null),
(57, 'berry_bush', 'Berry Bush', 'berry_bush.png', 0, null),
(58, 'coon_tail', 'Coon Tail', 'coon_tail.png', 0, null),
(59, 'deerclops_eye', 'Deerclops Eye', 'deerclops_eye.png', 0, null),
(60, 'koalefant_trunk', 'Koalefant Trunk', 'koalefant_trunk.png', 0, null),
(61, 'tentacle_spots', 'Tentacle Spots', 'tentacle_spots.png', 0, null),
(62, 'walrus_tusk', 'Walrus Tusk', 'walrus_tusk.png', 0, null),
(63, 'winter_koalefant_trunk', 'Winter Koalefant Trunk', 'winter_koalefant_trunk.png', 0, null),
(64, 'cactus_flower', 'Cactus Flower', 'cactus_flower.png', 0, null),
(65, 'mosquito_sack', 'Mosquito Sack', 'mosquito_sack.png', 0, null),
(66, 'moon_rock', 'Moon Rock', 'moon_rock.png', 0, null),
(67, 'health', 'Health', 'health.png', 0, null),
(68, 'fur_tuft', 'Fur Tuft', 'fur_tuft.png', 0, null),
(69, 'glommers_wings', 'Glommer''s Wings', 'glommers_wings.png', 0, null),
(70, 'glommers_flower', 'Glommer''s Flower', 'glommers_flower.png', 0, null),
(71, 'thulecite', 'Thulecite', 'thulecite.png', 0, null),
(72, 'thulecite_fragments', 'Thulecite Fragments', 'thulecite_fragments.png', 0, null),
(73, 'guardians_horn', 'Guardianshorn', 'guardians_horn.png', 0, null),
(74, 'yellow_gem', 'Yellow Gem', 'yellow_gem.png', 0, null),
(75, 'green_gem', 'Green Gem', 'green_gem.png', 0, null),
(76, 'orange_gem', 'Orange Gem', 'orange_gem.png', 0, null),
(77, 'egg', 'Egg', 'egg.png', 0, null),
(78, 'meat', 'Meat', 'meat.png', 0, null),
(79, 'watermelon', 'Watermelon', 'watermelon.png', 0, null),
(80, 'sand', 'Sand', 'sand.png', 0, null),
(81, 'obsidian', 'Obsidian', 'obsidian.png', 0, null),
(82, 'bioluminescence', 'Bioluminescence', 'bioluminescence.png', 0, null),
(83, 'seashell', 'Seashell', 'seashell.png', 0, null),
(84, 'bamboo', 'Bamboo', 'bamboo.png', 0, null),
(85, 'vines', 'Vines', 'vines.png', 0, null),
(86, 'palm_leaf', 'Palm Leaf', 'palm_leaf.png', 0, null),
(87, 'coconut', 'Coconut', 'coconut.png', 0, null),
(88, 'jellyfish', 'Jellyfish', 'jellyfish.png', 0, null),
(89, 'seaweed', 'Seaweed', 'seaweed.png', 0, null),
(90, 'snakeskin', 'Snakeskin', 'snakeskin.png', 0, null),
(91, 'venom_gland', 'Venom Gland', 'venom_gland.png', 0, null),
(92, 'coral', 'Coral', 'coral.png', 0, null),
(93, 'dead_swordfish', 'Dead Swordfish', 'dead_swordfish.png', 0, null),
(94, 'banana', 'Banana', 'banana.png', 0, null),
(95, 'dubloons', 'Dubloons', 'dubloons.png', 0, null),
(96, 'hail', 'Hail', 'hail.png', 0, null),
(97, 'shark_fin', 'Shark Fin', 'shark_fin.png', 0, null),
(98, 'brainy_matter', 'Brainy Matter', 'brainy_matter.png', 0, null),
(99, 'blubber', 'Blubber', 'blubber.png', 0, null),
(100, 'turbine_blades', 'Turbine Blades', 'turbine_blades.png', 0, null),
(101, 'rope', 'Rope', 'rope.png', 1, 133),
(102, 'limestone', 'Limestone', 'limestone.png', 1, 138),
(103, 'cut_stone', 'Cut Stone', 'cut_stone.png', 1, 135),
(104, 'electrical_doodad', 'Electrical Doodad', 'electrical_doodad.png', 1, 85),
(105, 'straw_hat', 'Straw Hat', 'straw_hat.png', 1, 165),
(106, 'empty_bottle', 'Empty Bottle', 'empty_bottle.png', 1, 141),
(107, 'boards', 'Boards', 'boards.png', 1, 134),
(108, 'torch', 'Torch', 'torch.png', 1, 141),
(109, 'gunpowder', 'Gunpowder', 'gunpowder.png', 1, 87),
(110, 'cloth', 'Cloth', 'cloth.png', 1, 137),
(111, 'papyrus', 'Papyrus', 'papyrus.png', 1, 136),
(112, 'straw_roll', 'Straw Roll', 'straw_roll.png', 1, 52),
(113, 'pickaxe', 'Pickaxe', 'pickaxe.png', 1, 1),
(114, 'spear', 'Spear', 'spear.png', 1, 94),
(115, 'log_suit', 'Log Suit', 'log_suit.png', 1, 97)
